<template>
    <v-main>
        <v-container class="d-flex flex-column w-75 justify-center align-center">
            <div>
                <p class="text-h2 my-2">The Community Showcase</p>
                <p class="text-h5 my-2 text-medium-emphasis">
                    Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
                </p>
                <v-text-field label="Search" variant="underlined" clearable class="my-4"></v-text-field>
            </div>
        </v-container>
    </v-main>
</template>
