const prompts = [
    "A robot made of flowers",
    "A castle floating in the clouds",
    "A mermaid playing a guitar",
    "A dinosaur wearing a bowtie",
    "A knight riding a hoverboard",
    "A giant penguin with a top hat",
    "A unicorn playing basketball",
    "A dragon playing a video game",
    "A cat riding a bicycle",
    "A giraffe playing the drums",
    "A penguin with a monocle",
    "A kangaroo with a surfboard",
    "A elephant playing the trumpet",
    "A snake wearing a tuxedo",
    "A panda playing the piano",
    "A lion with a mohawk",
    "A fox playing a saxophone",
    "A bear playing the violin",
    "A koala with a parasol",
    "A robot made entirely of flowers and holding a bouquet of roses",
    "A castle floating in the sky with a rainbow bridge connecting it to the ground",
    "A mermaid sitting on a rock in the ocean playing an acoustic guitar",
    "A dinosaur wearing a black bowtie and top hat while holding a cane",
    "A knight in shining armor riding a futuristic hoverboard over a cityscape",
    "A giant penguin wearing a red and white striped top hat and monocle",
    "A unicorn playing a game of basketball with a rainbow-colored ball",
    "A dragon playing a video game on a giant screen in a city park",
    "A cat wearing a helmet and riding a yellow bicycle through a park",
    "A giraffe playing a set of drums in a rock band",
    "A penguin wearing a monocle and tuxedo while holding a red rose",
    "A kangaroo riding a surfboard on a beach at sunrise",
    "A elephant wearing a hat and playing a trumpet in a jazz band",
    "A snake wearing a black tuxedo and bow tie, playing a saxophone",
    "A panda wearing a bowtie and playing a grand piano in a concert hall",
    "A lion with a brightly colored mohawk, playing a electric guitar",
    "A fox playing a saxophone in a swing band",
    "A bear wearing a bowtie and playing a violin in an orchestra",
    "A koala wearing a hat and holding a parasol while sitting in a tree",
    "A robot made entirely of flowers, with petals as its joints and pistils as buttons",
    "A castle floating high in the sky, surrounded by clouds and held up by balloons",
    "A mermaid playing a beautiful acoustic guitar on a rock in the ocean",
    "A dinosaur wearing a bowtie and top hat, enjoying a cup of tea",
    "A knight riding a hoverboard with a shield and sword in hand",
    "A giant penguin with a top hat and cane, playing the accordion",
    "A unicorn playing a game of basketball with a rainbow-colored ball",
    "A dragon playing a video game on a giant screen, using its fire breath to control the action",
    "A cat riding a bicycle with a basket full of fish",
    "A giraffe playing the drums in a rock band",
    "A penguin with a monocle and cane, conducting an orchestra",
    "A kangaroo with a surfboard, riding a wave in the ocean",
    "A elephant playing the trumpet, surrounded by other animals enjoying the music",
    "A snake wearing a tuxedo and top hat, performing magic tricks",
    "A panda playing the piano, surrounded by bamboo trees",
    "A lion with a mohawk, playing a guitar and singing in a punk rock band",
    "A fox playing a saxophone, surrounded by a jazz band",
    "A bear playing the violin in a classical orchestra",
    "A koala with a parasol, enjoying a picnic in a tree",
    "A giraffe with a bowtie, conducting a choir of birds",
    "A horse with a top hat, performing magic tricks",
    "A zebra with a guitar, playing in a country music band",
    "A sheep with a paintbrush, creating a masterpiece on a canvas",
    "A monkey with a camera, taking photos of the jungle",
    "A crocodile with a drum set, playing in a rock band",
    "A penguin with a ukulele, singing and strumming on a beach",
    "A deer with a microphone, singing in a pop band",
    "A squirrel with a violin, performing in a classical quartet",
    "A cat with a trumpet, playing in a jazz band",
    "A dog with a saxophone, performing in a blues band",
    "A lion with a DJ setup, mixing music in a club",
    "A bear with a harp, playing in a Celtic band",
    "A fox with a banjo, playing in a bluegrass band",
    "A kangaroo with a keyboard, playing in a pop band",
    "A snake with a mandolin, playing in a folk band",
    "A panda with a maracas, playing in a Latin band",
    "A giraffe with a sitar, playing in an Indian classical band",
    "A horse with a steel drum, playing in a reggae band",
    "A zebra with a trombone, playing in a marching band",
    "A sheep with a tuba, playing in a brass band",
    "A monkey with a triangle, playing in a percussion ensemble",
    "A crocodile with a trumpet, playing in a brass band",
    "A penguin with a ukulele, playing in a Hawaiian band",
    "A deer with a violin, playing in a string quartet",
    "A squirrel with a viola, playing in a chamber orchestra",
    "A cat with a xylophone, playing in a percussion ensemble",
]

export default prompts
